# Generated by Django 5.0 on 2023-12-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Хабра')),
                ('url', models.URLField()),
                ('last_parsed', models.DateTimeField(blank=True, null=True, verbose_name='Последний парсинг')),
                ('last_status', models.CharField(max_length=100, verbose_name='Статус последнего парсинга')),
                ('parse_interval_minutes', models.PositiveIntegerField(default=10, verbose_name='Интервал парсинга (минуты)')),
                ('is_active', models.BooleanField(default=False, verbose_name='On/Off')),
            ],
        ),
        migrations.CreateModel(
            name='ParserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_name', models.CharField(max_length=100, verbose_name='Имя парсера')),
                ('log_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата/Время сообщения')),
                ('log_text', models.TextField(blank=True, null=True, verbose_name='Текст лога')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date_collected', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения')),
                ('date_parsed', models.DateTimeField(blank=True, null=True, verbose_name='Дата парсинга')),
                ('last_status', models.CharField(max_length=100, verbose_name='Статус последнего парсинга')),
                ('parse_this', models.BooleanField(default=True, verbose_name='Спарсить')),
                ('header', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('article_text', models.TextField(blank=True, null=True, verbose_name='Текст статьи')),
                ('article_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('author_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор')),
                ('author_url', models.URLField()),
                ('habr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.habrs')),
            ],
        ),
    ]
