# Generated by Django 5.0 on 2023-12-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habrs',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название Хабра'),
        ),
    ]
