# Generated by Django 5.0 on 2023-12-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0002_alter_habrs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='last_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус последнего парсинга'),
        ),
        migrations.AlterField(
            model_name='habrs',
            name='last_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус последнего парсинга'),
        ),
    ]
