# Generated by Django 5.0 on 2023-12-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0003_alter_articles_last_status_alter_habrs_last_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='header',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Заголовок'),
        ),
    ]
