# Generated by Django 5.0 on 2023-12-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0004_alter_articles_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
